name: compile

on:
  pull_request:
  push:

jobs:
  compile:
    name: Compile Server & Studio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore
        run: |
          git clean -xfd
          dotnet restore

      - name: Build Server
        run: |
          dotnet build

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: 'src/Raven.Studio/.nvmrc'
          
      - name: Restore
        run: |
          npm install
          npm run restore
        working-directory: src/Raven.Studio

      - name: Compile Studio
        run: |
          npm run compile
        working-directory: src/Raven.Studio

